#include <hmg.ch>

// ******************************************************************************
// Crocciari, Daniel
// hmglights.wordpress.com
// danielcrocciari@gmail.com
//

function liberaComponentes()

   SETPROPERTY("main","text_pathOrigem","ENABLE",.t.)

   SETPROPERTY("main","text_pathOrigem","ENABLED",.t.)
   SETPROPERTY("main","text_pathDestino","ENABLED",.t.)
   SETPROPERTY("main","text_fileDestino","ENABLED",.t.)
   SETPROPERTY("main","text_fileextensao","ENABLED",.t.)
   SETPROPERTY("main","btPathOrigem","ENABLED",.t.)
   SETPROPERTY("main","btPathDestino","ENABLED",.t.)
   SETPROPERTY("main","btIniciarManual","ENABLED",.t.)
   SETPROPERTY("main","btIniciarAuto","ENABLED",.t.)
   
   SETPROPERTY("main","btPararAuto","ENABLED",.f.)

return nil