#include <hmg.ch>

// ******************************************************************************
// Crocciari, Daniel
// hmglights.wordpress.com
// danielcrocciari@gmail.com
//

Function Main

        public nInicio := seconds()
		public bAuto := .t.
		public nTempo := 60
		
		public pcPathOrigem := ""
        public pcPathDestino := ""
		public pcFileDestino := ""
        public pcTipoFileOrigem := ""

        Load Window Main
        Main.Center
        Main.Activate

Return


